name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/arm64,linux/amd64
        file: caddy-cloudflare/Dockerfile
        push: true
        tags: |
          ghcr.io/lakshanwd/caddy-cloudflare:latest
          ghcr.io/lakshanwd/caddy-cloudflare:2.7.4
